name: movie_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.12.2
  dio: ^5.4.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mongo_dart: ^0.10.0
  tmdb_api: ^2.2.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
